
service endpoints:
  coordinator:
    hostname: localhost
    port: 50001
  io:
    hostname: localhost
    port: 80
  describe:
    hostname: localhost
    port: 50002
  haiku generator:
    hostname: localhost
    port: 50003
