
service endpoints:
  coordinator:
    hostname: localhost
    port: 0
  io:
    hostname: localhost
    port: 0
  describe:
    hostname: localhost
    port: 0
  haiku generator:
    hostname: localhost
    port: 0
